"""Add analytics columns to Message and Conversation tables

Revision ID: 1f377566a7ba
Revises: 
Create Date: 2025-07-01 22:57:43.673387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f377566a7ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('overall_sentiment', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('conversations', sa.Column('energy_trend', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('stress_indicators', sa.JSON(), nullable=True))
    op.add_column('conversations', sa.Column('analyzed', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('last_analyzed_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('messages', sa.Column('energy_level', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('stress_level', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('satisfaction_level', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('analyzed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'analyzed')
    op.drop_column('messages', 'satisfaction_level')
    op.drop_column('messages', 'stress_level')
    op.drop_column('messages', 'energy_level')
    op.drop_column('messages', 'sentiment_score')
    op.drop_column('conversations', 'last_analyzed_at')
    op.drop_column('conversations', 'analyzed')
    op.drop_column('conversations', 'stress_indicators')
    op.drop_column('conversations', 'energy_trend')
    op.drop_column('conversations', 'overall_sentiment')
    # ### end Alembic commands ###
